dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: pKZrKjL6qk/cKQCXX6r9HQJ/IVieGHW6wMUpg5WYfOrSZgHpeHC6r9HHZNpSXfVMHjYEouYQKjxsSCYHzAvY5aKnJl31kD5eUzQMXyKffYctu/wq766JKQEHmlFiN1vcoqlh6amv4+usUeg+Xg1X0xAX0rzfR8MrHTYvnuNTBTSb8EWvGv5g+N8OGvcsoRHg1aKxfnoarpPe4NBsd2PgersK95vFIEkhguCP8IKtNQJCSh2z3mAKAtKN2KCp2eEGjJYFsyCtEG49j+a6iPTpBEKh9x6tNfd0a/lG8C9YX2goG1tnOofgW6KDj6fukdle/B3pqboy/hKbPavYn8oc82E+X755ybvMUYdv005OOjQppv/NpOgV9MV7ExTI3gwxfrDKFObkPTRX945frFXtc8b23Eaai5u6qYxLd9/DgNC3d+YjXrb5qIIIStqjnZ65QyUxHjldduj7HecOwb3CuI2aTq/oEA741tkdGeBG2zkBBtbqxTfTXQ62nhJaNpE0+43QEA9MUFYRtmbmqIyNnrejyNwqNkINevDKFNmbPXHySBnU97RtjT7BydJ2IffT08SYlUa3jXzftzAa3Wt0GfplGCtDFoapoVlF2v3y0a7jfJKdMQbgCRQchOLkA9bPK9a5H1qx5loAVoqroymV9Xs48Nzj0xZBB4Tnbc2nQMI=
