dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: gll8pyGGb6RMKmfyLIIiSrXxniocUtzkrlIHUqYbaMmc2dSYNTsmoZj2LR9zHhBjpyQCquhCawyDNcf/D+B1pebGUrj9EoQ1NlVJSY2yQuq0L7nN0zv83cI30Ei5JaZp/E/itiSDgVeW7ukFmytt8KkNmZvT7MR17uwpEw2EAu8X4EMOm3mg8QKD8+xAchSjpAJXsqstUHcebUVrR3vQG1JvUnOkToSs335DsugQfhe3oZV6uwI50aRNlZ+WHv8M+kr0Va70AoZqmvpcf5UHbjha5SdmIvXdzRw5uf68Wrr6jfHCA+mYXr+OtK7QApIFuvXGTkNZtswtW9axuQ0RxsCxPuBNGrXwBzJj0h9BtOSskehKlZR6IXqPA+1ndSQdKSAV6+ae4X+Am9MELRafBb+/mwsROA8byyGKVaejfI7QdbnsxcN7dl5svWHoe1tsyMOEpDSXeQUM9T3W7gjhnyeAGZUz0D74N6NtqACzi5a7mtUZLI8G4JyOYzmT2Rpvf/a+rfRGwj5bEvYNR54QGcca8d+BMiWXs8FXAByStHM4D7dhr5ODoTMTYHlWBKOt6BtlNZV4t2Y4rmbXmFtTSdo2GiVYhsU2yw1lpagvjyGZgiEkpGP/nYKRfzE/qo/BrXMxhgVMoOCwlMmU11lnE2cWLAz40xJTUchV2h9uDlk=
