dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: fzp4Imzt+Sd3j4wCqD/0V8obu4L+q9Z9PKHoKzymZmJcODP8M/zTIinj7lySm3Bssxd77bkwyt2AVn4W1p00a6QFz07txTmAFXQXbOOVUF+yZrOfR58TF1yiOFrFx0++X+m4G4v73Mlfh8C416VHPQ0Xf11jFe/4IKzn8HtKKJhiJXcRRkRuNYtyNYHxgmc74cHqaIBMMB5fOFcNj5Ot1Q+En5SRxn9oQ9PRSX/oaIPtrxRLPxXfxKT0q4MG5cGeQgpubkuJWSUuOC74P1+aFUoKIKSd79VMPhXMVBCCG0KTgoSEdNH6nim1VBnpMwhYuhsmbXTxaIVZgiYA4/3gsAagXMN/qpqmbKtaQYDTsmoSFKkjuP7PAUUldciSczaph/tgB5/NQS/gBIyGdgyeWhUfVVPMYYzX/zXTPcaVKgn2GL/TOGGRbOmZTp5/cTLo+BjX+DA38aZZvXhUwd1ZBJa1Op8uh8TBZIwg24H531ElMewUKeoiUmrcgSGuvTL5AcCI6Xfn/FP321LIpBvjvDAmryv2r3Jp9c5wpPSxUNlD4x/fAeyYukH0+9s1epgGXwgjMINJDHq0s96NgxhqKej7H3FsTzLcQAWMfefW8SmIAkbAquCatOUveOVbhj05A4Zy94cOy47l4JA7r6MCRuXEitftU/DbZPFgLEbD2Nc=
